application:
  version: @project.version@
  name: @project.name@ Server
  
apiHostName: https://concessions.connors.ddns.net
authHostName: login.connors.ddns.net

local:
    network:
        server: true